apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: arm64
spec:
  template:
    spec:
      nodeClassRef:
        name: arm64
      requirements:
        - key: "kubernetes.io/arch"
          operator: In
          values: ["arm64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot","on-demand"]
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["c6g.large","m6g.large"]
