apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: x86
spec:
  template:
    spec:
      nodeClassRef:
        name: x86
      requirements:
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot","on-demand"]
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["c6i.large","m6i.large"]
